[Build] AppImage
Mr-Wiseguy/Zelda64Recomp pull request #231
Opened 2024-05-21 02:05 UTC by qurious-pixel

Adds AppImage build.

Fixes https://github.com/Zelda64Recomp/Zelda64Recomp/issues/21

2024-05-21 09:07 UTC, dcvz commented on .github/workflows/validate.yml
> +      - name: Zelda64Recomp AppImage
This will run in both Debug and Release - but you use one name for the archive, so the file will be overwritten by whichever finishes last. You'll want to differentiate the names as we do in the step before.

2024-05-21 09:13 UTC, dcvz commented on .github/workflows/validate.yml
> +          name: Zelda64Recompiled-AppImage
This will run in both Debug and Release - but you use one name for the archive, so the file will be overwritten by whichever finishes last. You'll want to differentiate the names as we do in the step before.

2024-05-21 09:13 UTC, dcvz commented on .github/workflows/validate.yml
> +          name: Zelda64Recompiled-AppImage
```suggestion
          name: Zelda64Recompiled-AppImage-${{ matrix.type }}
```

2024-05-21 10:13 UTC, dcvz commented
The game expects an assets folder to be present - see the GitHub workflow step where we prepare it. The AppImage does not run for me atm due to the missing assets folder.

2024-05-21 10:18 UTC, dcvz requested changes
Thanks for the contribution @qurious-pixel! The game expects the assets folder to be present - see the GitHub workflow step where we prepare it. The AppImage does not run for me due to the missing assets folder.

2024-05-21 13:03 UTC, dcvz commented
@qurious-pixel does the app image work for you locally after your changes?

2024-05-21 13:52 UTC, qurious-pixel commented
> @qurious-pixel does the app image work for you locally after your changes?

Yes. i have updated on my repo. 
https://github.com/qurious-pixel/Zelda64Recomp/releases/tag/LinuxRelease

Had to change the way Zelda64Recomp accesses the assets folder.

2024-05-21 13:58 UTC, Reonu requested changes
The AppImage does not work for me on EndeavourOS (whereas the normal Linux build that Wiseguy provides does work, as well as building it myself).

The AppImage gives me this error:
`SDL error opening audio device: Audio subsystem is not initialized`

2024-05-21 14:20 UTC, qurious-pixel commented
> The AppImage does not work for me on EndeavourOS (whereas the normal Linux build that Wiseguy provides does work, as well as building it myself).
> 
> The AppImage gives me this error: `SDL error opening audio device: Audio subsystem is not initialized`

I will rework the appimage. my EndeavourOS is too old because of the libc requirements, which I want to replace, but have to fix gcc or get musl-clang working.

2024-05-21 14:20 UTC, dcvz commented
> > @qurious-pixel does the app image work for you locally after your changes?
> 
> Yes. i have updated on my repo. https://github.com/qurious-pixel/Zelda64Recomp/releases/tag/LinuxRelease
> 
> Had to change the way Zelda64Recomp accesses the assets folder.

I get the same audio error on the Steam Deck. Also I don’t see the changes to asset loading in the changes here.

2024-05-21 18:50 UTC, qurious-pixel commented
I wasnt properly passing the audio driver headers to the SDL2 source files, so it was building with "dummy" sound drivers.
Pushing the proper fix once I can verify my build. 
 
`Dummy sound drivers`
![withoutsound](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/62252937/466bc309-088b-4299-8f0d-12c7b1915a21)

`Complete sound drivers`
![withsoundfiles](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/62252937/10b65835-cf6e-471a-a71f-fef7f79957f3)

2024-05-21 20:19 UTC, dcvz commented
@qurious-pixel the last AppImage does work for me on the Steam Deck!

2024-05-21 22:54 UTC, dcvz commented
@qurious-pixel but you seem to be missing the changes you had to make, no?

2024-05-21 23:06 UTC, qurious-pixel commented
> @qurious-pixel but you seem to be missing the changes you had to make, no?

I was missing on my branch, the PR already had the changes.

2024-05-22 08:53 UTC, dcvz approved these changes
I've generated an AppImage from this branch and its working well!

2024-05-22 08:55 UTC, merged

2024-05-22 09:06 UTC, dcvz commented
Thank you for the contribution @qurious-pixel !