Use shader_cache 1.1.0 in artefacts
Mr-Wiseguy/Zelda64Recomp pull request #272
Opened 2024-05-26 19:05 UTC by dcvz

2024-05-26 19:05 UTC, dcvz commented on .github/workflows/validate.yml
> +  pull_request:
Used to test this pipeline, to be reverted before merge.

2024-06-01 19:04 UTC, Mr-Wiseguy requested changes

2024-06-01 19:04 UTC, Mr-Wiseguy commented on .github/workflows/validate.yml
> +          tar -czf Zelda64Recompiled-${{ runner.os }}-${{ matrix.type }}.tar.gz Zelda64Recompiled assets/ shadercache/
The shader cache is embedded into the binary, so there's no need to copy it into the final archive

2024-06-01 19:04 UTC, Mr-Wiseguy commented on .github/workflows/validate.yml
> +            shadercache/
Ditto from the other comment.

2024-06-01 19:04 UTC, Mr-Wiseguy commented on .github/linux/appimage.sh
> +cp -r shadercache/ AppDir/usr/bin/
Same deal as the other comments

2024-06-02 18:18 UTC, Mr-Wiseguy approved these changes

2024-06-02 18:18 UTC, merged