build: ensure assets are copied to cmake binary directory
Mr-Wiseguy/Zelda64Recomp pull request #361
Opened 2024-06-05 01:51 UTC by briaguya-ai

this prevents needing to manually copy assets over to avoid a "Document for menu not loaded!" error

i haven't done a deep dive into how this impacts ci, but it seems as though the workflows there interact with the build directory on a file-by-file basis when packing so i'm thinking this is effectively a dev env only change

2024-06-06 07:48 UTC, dcvz approved these changes
LGTM 👍

2024-06-06 10:29 UTC, dcvz requested changes
Looks like CI has an issue with this

2024-06-06 11:20 UTC, briaguya0 commented
looks like `copy_directory_if_different` was [added in `3.26`](https://cmake.org/cmake/help/latest/manual/cmake.1.html#cmdoption-cmake-E-arg-copy_directory_if_different)

i guess there are a couple options here
* wrap it in `if (CMAKE_VERSION VERSION_GREATER_EQUAL "3.26.0")`
* update the minimum cmake version
  * i tend to agree with the "Picking a CMake Version" section [in this blog post](https://alexreinking.com/blog/how-to-use-cmake-without-the-agonizing-pain-part-1.html) - new versions are good, and if the goal is to have [ci build on old distros like ubuntu `18.04`](https://github.com/Zelda64Recomp/Zelda64Recomp/pull/346) then having ci install via pip or a third party apt repo or even snap feels more reasonable than limiting cmake functionality to very old versions (`20.04`'s [repos have `3.16`](https://packages.ubuntu.com/focal/cmake) and the minimum is already [set to `3.20`](https://github.com/Zelda64Recomp/Zelda64Recomp/blob/b0d0cab6c2f6a108fc04fd1aa0ac80073a7e9a39/CMakeLists.txt#L1))
* look into using a command that works in `3.20` - some combo of globbing and [`make_directory`](https://cmake.org/cmake/help/latest/manual/cmake.1.html#cmdoption-cmake-E-arg-make_directory) and [`copy_if_different`](https://cmake.org/cmake/help/latest/manual/cmake.1.html#cmdoption-cmake-E-arg-copy_if_different)

i'm more than happy to update this in any of those ways, and if you have another idea i haven't suggested i'll gladly try that too

2024-06-09 02:32 UTC, briaguya-ai commented
@dcvz any thoughts on the best way to proceed with this?

2024-06-09 02:55 UTC, Mr-Wiseguy commented
Personally I think the best option of those 3 would be to elevate the minimum CMake, but my bigger question is about the necessity of this in the first place. Personally, I always run the binary out of the project root directory, which happens automatically in Visual Studio on Windows via the launch.vs.json file. It can also be automated in VSCode if using the CMake tools extension, though I haven't messed with it much so it's not set up currently. For building with command line, you can do `cmake --build [build folder]` and then run it via `[build folder]/Zelda64Recompiled` to get the same effect as well. I don't feel too strongly for or against this change right now, but I would probably want to hear a reason that makes those solutions inadequate before merging this.

There's also something to consider with the scss folder in the assets, which just contains input files that are built into recomp.rcss and isn't actually used by the binary directly or distributed in builds. It might be a good idea to exclude that folder to reduce the number of files that the build system has to check on every build, since that would reduce the iterative build time overhead this change adds (assuming it's any measurable amount).

2024-06-09 06:01 UTC, briaguya-ai commented
yeah, it may just be something where having a vscode cmake tools launch.json documented would be the better move, it's just nice when the [launch.json-less method](https://github.com/microsoft/vscode-cmake-tools/blob/main/docs/debug-launch.md#debugging-without-a-launchjson) works, but this launch.json (based off the [gdb specific one from the extension docs](https://github.com/microsoft/vscode-cmake-tools/blob/main/docs/debug-launch.md#gdb)) seems to do the trick

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            // Resolved by CMake Tools:
            "program": "${command:cmake.launchTargetPath}",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [
                {
                    // add the directory where our target was built to the PATHs
                    // it gets resolved by CMake Tools:
                    "name": "PATH",
                    "value": "${env:PATH}:${command:cmake.getLaunchTargetDirectory}"
                },
            ],
        }
    ]
}
```

2024-06-09 06:01 UTC, closed without merging

2024-06-09 09:09 UTC, dcvz commented
If you use Clion or VSCode, by default it will launch out of the build folder. You can probably change it as you have with the launch file but others would have to figure that that's the solution. I don't mind getting this in as it'll cover more building scenarios but on the other we can just document it.