feat: allow configuring menu accept button
Mr-Wiseguy/Zelda64Recomp pull request #385
Opened 2024-06-09 08:47 UTC by briaguya-ai

resolves https://github.com/Zelda64Recomp/Zelda64Recomp/issues/372 by following the pattern from https://github.com/Zelda64Recomp/Zelda64Recomp/pull/181 as recommended in https://github.com/Zelda64Recomp/Zelda64Recomp/issues/372#issuecomment-2151031399

there are a couple extra things in here too, i've left a self review with comments explaining those changes

2024-06-09 09:00 UTC, briaguya-ai reviewed
![Screenshot from 2024-06-09 04-30-32](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/70942617/64bf0f09-8490-49a2-83bc-9b4ce94632a0)
![Screenshot from 2024-06-09 04-30-45](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/70942617/25bd7ae6-c745-49ee-8398-07bb3a18bf90)

2024-06-09 09:00 UTC, briaguya0 commented on include/recomp_input.h
> +        DEFINE_INPUT(ACCEPT_MENU, 0, "Accept (Menu)")
not sure about this name, very open to suggestions for better ones

2024-06-09 09:00 UTC, briaguya0 commented on src/game/input.cpp
> +        return PF_GAMEPAD_A;
just moving away from magic strings here

2024-06-09 09:00 UTC, briaguya0 commented on src/game/input.cpp
> +        return PF_ICON_XBOX;
on linux it is possible to map this button, and i personally like using it to open the recomp menu, before this change that means my menu would look like

![Screenshot from 2024-06-09 04-20-10](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/70942617/aee28ebc-50e7-4519-a761-0fb60947e388)
![Screenshot from 2024-06-09 04-20-17](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/70942617/b9446284-088b-45f5-b2bc-15f68b0675e5)

based on the pattern of using the xbox glyphs for the other button mappings, i switched this to the xbox icon so instead it looks like

![Screenshot from 2024-06-09 04-21-05](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/70942617/58fc118a-f3f4-4a5d-b9af-ca5be07d0363)
![Screenshot from 2024-06-09 04-21-21](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/70942617/869bd4c3-5189-45c1-a911-69d8d794f68e)

2024-06-09 09:00 UTC, briaguya0 commented on src/game/input.cpp
> +    {SDL_SCANCODE_RSHIFT, PF_KEYBOARD_SHIFT},
without this the keyboard mappings appear as

![Screenshot from 2024-06-09 04-43-36](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/70942617/0a505735-c79c-4270-82c3-09b967cfc595)
![Screenshot from 2024-06-09 04-43-27](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/70942617/5135bb9f-875c-4ad3-8ff6-0d9bac5487a1)

with this they are instead

![Screenshot from 2024-06-09 04-42-31](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/70942617/ade32485-0f8f-459b-b537-6c31ca712bea)
![Screenshot from 2024-06-09 04-42-18](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/70942617/07113327-a5a9-47a0-a529-8931629e802a)

2024-06-09 09:00 UTC, briaguya0 commented on src/ui/ui_config.cpp
> +	nav_help_model_handle.DirtyVariable("nav_help__exit");
this makes sure the bottom bar icons are updated to match what is mapped (missed this when adding the configurable toggle)

2024-06-09 09:00 UTC, briaguya0 commented on src/ui/ui_config.cpp
> +	nav_help_model_handle.DirtyVariable("nav_help__exit");
this might not actually be needed but i saw `inputs` being dirtied here so i figured there might be something i'm not aware of

2024-06-09 09:00 UTC, briaguya0 commented on src/ui/ui_config.cpp
> +					recomp::get_input_binding(recomp::GameInput::TOGGLE_MENU, 1, recomp::InputDevice::Controller).to_string();
missed this when doing the toggle menu PR

2024-06-09 17:55 UTC, Mr-Wiseguy commented on src/game/input.cpp
> +    {SDL_SCANCODE_RSHIFT, PF_KEYBOARD_SHIFT},
My concern with this one is that it doesn't indicate that only left or right shift works with this. I'd rather wait until we have a proper left/right shift icon, or maybe we can do `"L" PF_KEYBOARD_SHIFT` and `"R" PF_KEYBOARD_SHIFT` for now in the meantime.

2024-06-09 18:00 UTC, Mr-Wiseguy commented on src/game/input.cpp
> +        return PF_ICON_XBOX;
While xbox icons are used for other inputs, they're still generic for the most part. I think this would be better with the "Home/Menu" promptfont icon to avoid confusion with other controllers:
![image](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/68165316/61f1cf7b-75ba-472d-92e7-81dbc4a63b41)

2024-06-09 18:02 UTC, Mr-Wiseguy commented on src/ui/ui_config.cpp
> +	nav_help_model_handle.DirtyVariable("nav_help__exit");
Doesn't hurt to have it so might as well.

2024-06-09 18:03 UTC, Mr-Wiseguy requested changes
Thanks! Looks good, just the couple things I mentioned

2024-06-09 18:03 UTC, Mr-Wiseguy commented on include/recomp_input.h
> +        DEFINE_INPUT(ACCEPT_MENU, 0, "Accept (Menu)")
I think this name works fine

2024-06-09 18:42 UTC, briaguya-ai commented on src/game/input.cpp
> +    {SDL_SCANCODE_RSHIFT, PF_KEYBOARD_SHIFT},
i'd much prefer L + Icon and R + Icon to just a giant 225, i'll do that

2024-06-09 18:47 UTC, briaguya-ai commented on src/game/input.cpp
> +        return PF_ICON_XBOX;
sounds good, curious as to the reasoning behind the xbox icons for
![image](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/70942617/bcc385d2-d1cc-42c5-8050-f928cce28c1d)
and
![image](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/70942617/2c2a1dbc-1f31-42cc-ae88-1e4730bd3b03)

instead of the more generic

![image](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/70942617/4898a63d-0375-472c-95e6-d132d0f30100)

2024-06-09 18:53 UTC, Mr-Wiseguy commented on src/game/input.cpp
> +        return PF_ICON_XBOX;
Mainly because I thought the text below them might be too small to read, plus the Steam Deck matching the current icons is a nice bonus. The home button we're switching the guide button to at least has the home icon on it, so even if the text is too hard to read you can still tell it's the home button from that. Ideally we'd use a circular button with a home icon it to match the shape of these two, but I don't see anything like that in promptfont.

2024-06-09 19:02 UTC, briaguya-ai commented on src/game/input.cpp
> +    {SDL_SCANCODE_RSHIFT, PF_KEYBOARD_SHIFT},
i don't love it but i still prefer it to **255**

![image](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/70942617/0f06e83c-d68f-4804-b514-8b1faf4ba187)

2024-06-10 18:28 UTC, briaguya-ai commented on src/game/input.cpp
> +        return PF_ICON_XBOX;
addressed in https://github.com/Zelda64Recomp/Zelda64Recomp/compare/2162e91966ed95b4b7da6b3ea00d083457a91e48..4c0a534752552a775c277bc9df5fbb06178eb221

2024-06-10 18:28 UTC, briaguya-ai commented on src/game/input.cpp
> +    {SDL_SCANCODE_RSHIFT, PF_KEYBOARD_SHIFT},
addressed in https://github.com/Zelda64Recomp/Zelda64Recomp/compare/2162e91966ed95b4b7da6b3ea00d083457a91e48..4c0a534752552a775c277bc9df5fbb06178eb221

2024-06-11 02:33 UTC, Mr-Wiseguy commented
I gave this a test and it does work, but I noticed one oversight which is that it becomes impossible to do anything in the menu if you map accept to a button that has fixed handling in `cont_button_to_key`, since that switch case takes priority over the accept button. I think it'd be best for accept to have the highest priority since getting into a situation where you can't do anything in the menu isn't ideal.

2024-06-11 05:07 UTC, briaguya-ai commented
> getting into a situation where you can't do anything in the menu isn't ideal

yeah, this is also currently possible if someone hits the clear button on the mapping (trash can icon), but at least in that situation it would be clear *why* nothing is working

overall i'm not 100% sure what the best overall ux for configurable menu buttons is, but i have a couple ideas and i think expanding the scope of this PR may be worth doing
* add "Apply (Menu)" as a configurable button
  * update button on graphics screen to use glyphs based on mapping
* update clear button on menu action mappings to reset to default instead of clearing
  * the trash can icon would make this confusing, so displaying something that better represents "reset" for those would be ideal
  * if "Apply (Menu)" is added as configurable and defaults to having both west and start as defaults, mapping apply to only a single button would be impossible
    * possibly change the default to only be one button?
* make it so dpad directions and joystick axis directions can't be mapped to any menu actions

2024-06-11 05:42 UTC, Reonu commented
Replacing the trashcan button with a reset button for this particular action sounds ideal to me

2024-06-12 18:50 UTC, briaguya-ai commented
i'm thinking through how to handle the reset button for menu actions

consider the following scenario (assuming apply's default is changed to just be one button)

| action | default | remapped to |
| - | - | - |
| toggle menu | back/select | start | 
| accept | south | back/select |
| apply | start | south |

for manually setting mappings i think just blocking the user from setting a mapping that is already associated with an existing menu action should suffice

for the reset button it gets a bit more complicated. if a user tried to hit reset for the apply action in this scenario what should happen?
* the user is blocked from resetting to start because start is already mapped to toggle menu?
* the reset cascades through?
  * apply resets to start - triggers a reset on any menu action set to start (in this case toggle menu)
  * toggle menu resets to back/select - triggers a reset on any menu action set to back/select (in this case accept)
  * accept resets to south - triggers a reset on any menu action set to south (in this case nothing)

i think i'm leaning towards just blocking the reset in that case, thoughts?

2024-06-16 20:24 UTC, Mr-Wiseguy commented
Blocking the reset would need some sort of feedback to the user so they can know why it didn't do anything, otherwise I think it'll just lead to confusion.

I think reset leading to doubled bindings is fine, as long as accept is always the highest priority input. If you can press the accept button then you can always fix the other bindings manually, since you can navigate to them and use accept to redo the bindings for toggle menu and apply. Worst case scenario is that somebody locks themselves out of being able to open the menu while in-game, but even in that case they can reopen the program and navigate to the binding menu from the launcher menu as long as accept is still bound. How do you feel about that solution?

As for not being able to remove one of the Apply bindings if it defaults to two bindings and only has a reset button, I think that's fine to leave with a delete button. Apply is effectively an optional binding, it doesn't do anything that you couldn't already do with accept and navigation.

2024-06-17 06:17 UTC, briaguya-ai commented on assets/icons/Reset.svg
this is from https://fonts.google.com/icons?selected=Material+Symbols+Outlined:refresh:FILL@0;wght@400;GRAD@0;opsz@40&icon.query=refresh&icon.size=32&icon.color=%23e8eaed

i couldn't figure out where any of the other icons in this directory came from, if i knew i would have looked for a reset icon from whatever set they're from instead

2024-06-17 06:59 UTC, briaguya-ai commented
> I think reset leading to doubled bindings is fine, as long as accept is always the highest priority input. If you can press the accept button then you can always fix the other bindings manually, since you can navigate to them and use accept to redo the bindings for toggle menu and apply.

i've implemented this and overall i'm happy with it, but thinking about it now i realized there are a couple possible edge cases i didn't handle:
* binding an analog stick direction to menu actions - it is currently possible and there is no logic in the analog stick section to check for it - making it possible to get into a situation where an analog stick direction is mapped to accept and accept no longer works
* binding a dpad direction (down) to accept - if someone has a controller without an analog stick they would be unable to navigate down to change the accept mapping

part of me thinks it makes sense to prevent mapping dpad/analog stick directions to accept, but i know some controllers end up with really silly mappings and being able to address that in-game instead of telling a player to add something to gamecontrollerdb.txt would be preferable imo.

overall i think adding logic to `cont_axis_to_key` to handle the edge case of someone having a button that shows up as an axis (happens with some n64 adapters for c buttons) being able to map those to menu actions seems reasonable, but that doesn't cover the "i mapped a dpad direction on my SNES controller to accept and now i can't navigate the menu" situation

2024-06-21 20:03 UTC, Mr-Wiseguy commented
I agree that preventing directional mappings for accept makes sense here. We're going to be curating our own game controller DB with the problematic controllers people are reporting (since the regular gamecontrollerdb.txt seems to not play well with the cardinal direction SDL hint that recomp uses), so I wouldn't worry about the SDL mapping getting in the way of being able to bind the right physical button to a given input.

2024-06-22 13:04 UTC, briaguya-ai commented
i got it to a point where it blocks dpad directions properly with https://github.com/Zelda64Recomp/Zelda64Recomp/compare/916537e24d2f31a3726c1c2e63460874f52a4187..b9a7b81a1c61d0799898573b0da9771537e4d68b but i ran into issues blocking analog because of https://github.com/Zelda64Recomp/Zelda64Recomp/issues/411

i've put this back into draft for now

2024-06-23 23:58 UTC, briaguya-ai commented
alright, i think i've finally gotten this to a point where everything is working as expected

2024-06-27 22:31 UTC, Mr-Wiseguy approved these changes
This is very solid now, lgtm. I'll give thecozies a chance to review it before merging since he's working on the UI refactor, though the refactor shouldn't touch this menu much.

2024-07-02 14:30 UTC, thecozies requested changes
after this icon swap lgtm!

2024-07-02 14:30 UTC, thecozies commented on assets/icons/Reset.svg
> +<svg xmlns="http://www.w3.org/2000/svg" height="40px" viewBox="0 -960 960 960" width="40px" fill="#e8eaed"><path d="M480-160q-133.33 0-226.67-93.33Q160-346.67 160-480q0-133.33 93.33-226.67Q346.67-800
i made a new icon to match the others, would you mind swapping with this one?

```suggestion
<svg width="32" height="32" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
    <path d="M27.6949 10.3162C25.5859 5.98481 21.1415 3 16 3C8.8203 3 3 8.8203 3 16C3 23.1797 8.8203 29 16 29C21.1415 29 25.5859 26.0152 27.6949 21.6838" stroke="#FFFFFF" stroke-width="4" stroke-linecap="round"/>
    <path d="M29.052 11.0519V5.0519" stroke="#FFFFFF" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/>
    <path d="M29.052 11.0519H23.052" stroke="#FFFFFF" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/>
</svg>
```
![Reset](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/79979276/321ee599-a94d-4d4e-89d5-3288c9d805a2)

2024-07-06 01:17 UTC, thecozies approved these changes
thanks for updating!

2024-07-06 01:18 UTC, Mr-Wiseguy approved these changes

2024-07-06 01:19 UTC, merged

2024-07-06 01:19 UTC, Mr-Wiseguy commented
Thanks for the contribution, and especially for bearing with us as this PR got more complicated than any of us expected!