add option to skip sos cutscene
Mr-Wiseguy/Zelda64Recomp pull request #409
Opened 2024-06-21 15:07 UTC by danielryb

This pull request adds an option to skip the Song of Soaring cutscene with the A button.

https://github.com/Zelda64Recomp/Zelda64Recomp/assets/59661841/670a6963-9ea9-4fb4-9da7-2e6f11875dd5

This closes #396.

2024-06-21 16:38 UTC, Mr-Wiseguy requested changes
Thanks for the PR, this is great! Everything looks good and works well, just the one suggestion.

2024-06-21 16:38 UTC, Mr-Wiseguy commented on patches/skip_sos.c
> +    if (CHECK_BTN_ALL(input->press.button, BTN_A) && OWL_WARP_CS_GET_OCARINA_MODE(&this->actor) != ENTEST7_ARRIVE) {
I think it would make sense for B to also work for skipping the cutscene.

2024-06-22 22:49 UTC, danielryb commented on patches/skip_sos.c
> +    if (CHECK_BTN_ALL(input->press.button, BTN_A) && OWL_WARP_CS_GET_OCARINA_MODE(&this->actor) != ENTEST7_ARRIVE) {
Added.

2024-06-23 02:02 UTC, Mr-Wiseguy approved these changes

2024-06-23 02:02 UTC, merged

2024-06-23 02:02 UTC, Mr-Wiseguy commented
Approved and merged, thanks again!