Reset game from menu
Mr-Wiseguy/Zelda64Recomp pull request #513
Opened 2024-11-24 22:00 UTC by LT-Schmiddy

Adds an button to the config menu that returns the player to the main menu, with confirmation prompt and a fade to black transition. The button is right next to the quit game option in the config menu.

2024-11-24 23:32 UTC, Mr-Wiseguy requested changes

2024-11-24 23:32 UTC, Mr-Wiseguy commented on src/game/recomp_api.cpp
> +void zelda64::enqueue_game_reset() {
Just personal preference, but "enqueue" makes it sound like you could queue up multiple resets. I think something like "trigger_game_reset" would be better.

2024-11-24 23:32 UTC, Mr-Wiseguy commented on assets/config_menu.rml
> +            <button
Whitespace issue here, should be tabs instead of spaces for this file.

2024-11-24 23:32 UTC, Mr-Wiseguy commented on patches/game_patches.c
> +#include "game_patches.h"
I think it'd be better for this file and the corresponding header to be named `gamestate_patches`, since `game` isn't very specific. The other header is `zelda_game.h` because it's where all gameplay related functions are declared, so it's more generic than this file.

2024-12-18 21:27 UTC, LittleCube-hax requested changes
Fantastic work, hopefully this'll be the last round of changes before merging 😋

2024-12-18 21:27 UTC, LittleCube-hax commented on assets/config_menu.rml
> +              data-if="reset_button_visibility"
One last whitespace change to align the `data-if` with the others.

2024-12-18 21:27 UTC, LittleCube-hax commented on src/ui/ui_renderer.cpp
> +            }
Extra whitespace here

2024-12-18 21:27 UTC, LittleCube-hax commented on patches/play_patches.c
> +    recomp_set_reset_button_visibility(0);
Might want to add a comment annotating this call. As an example:
```C
// @recomp reset button should not be visible on PlayDestroy
recomp_set_reset_button_visibility(0);
```

2024-12-18 21:27 UTC, LittleCube-hax commented on patches/title_patches.c
> +    recomp_set_in_title_sequence(true);
Add a comment for this one too

2024-12-18 21:27 UTC, LittleCube-hax commented on patches/options.c
> +    recomp_set_in_title_sequence(false);
Add a comment for this one too

2024-12-18 21:27 UTC, LittleCube-hax commented on src/ui/ui_config.cpp
>                  zelda64::open_quit_game_prompt();
Indentation issue here too

2024-12-18 21:49 UTC, LT-Schmiddy commented on src/ui/ui_renderer.cpp
> +            }
Dang, thought I fixed this one.

2024-12-27 20:24 UTC, LittleCube-hax commented on src/ui/ui_config.cpp
>                  zelda64::open_quit_game_prompt();
I just now realized this isn't in the green 🥴 my mistake, this was already here.

2024-12-31 22:41 UTC, LittleCube-hax requested changes
A few _wildly_ picky things, but these changes are getting to be very good quality now.

2024-12-31 22:41 UTC, LittleCube-hax commented on patches/play_patches.c
> +    }
I think I may have missed this one last time, but it'd be good to annotate this change as well.

2024-12-31 22:41 UTC, LittleCube-hax commented on src/game/recomp_api.cpp
> +}
Incredibly nitpicky, but remove the extra newline at the end of this function.

2024-12-31 22:41 UTC, LittleCube-hax commented on patches/play_patches.c
> +    }
Try to add an annotation for this `if`, otherwise it might look like it's part of the event.

2024-12-31 23:03 UTC, LittleCube-hax approved these changes

2025-04-08 00:30 UTC, VelocityRa commented
Bump?

2025-04-08 00:44 UTC, LT-Schmiddy commented
I believe this PR will need to be rewritten, as there a substantial changes
to how 1.2 handles menus.

On Mon, Apr 7, 2025, 8:30 PM Nick Renieris ***@***.***> wrote:

> Bump?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Zelda64Recomp/Zelda64Recomp/pull/513#issuecomment-2784928465>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BKAUWUYRVSRJ6QMBMKSLOE32YMKCLAVCNFSM6AAAAABSMVSEECVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDOOBUHEZDQNBWGU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
> [image: VelocityRa]*VelocityRa* left a comment
> (Zelda64Recomp/Zelda64Recomp#513)
> <https://github.com/Zelda64Recomp/Zelda64Recomp/pull/513#issuecomment-2784928465>
>
> Bump?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Zelda64Recomp/Zelda64Recomp/pull/513#issuecomment-2784928465>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BKAUWUYRVSRJ6QMBMKSLOE32YMKCLAVCNFSM6AAAAABSMVSEECVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDOOBUHEZDQNBWGU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2025-04-28 06:35 UTC, Mr-Wiseguy commented
As we discussed offline, I'll be closing this PR in favor of a different approach that will be done in the future for a couple of reasons. The main reason being that this approach requires changes to the game which I'd prefer not to do since it'll make it more difficult to integrate into other recomps and will also get in the way of mods that need to patch the same functions. The future approach will return you to the launcher, which I consider more useful (since you'll be able to configure mods without restarting the program) and will also work out of the box with other recomps. The infrastructure needed to do this on the runtime side isn't there yet, so we'll have to hold off for now. The other main reason is that this menu will be rewritten to use the new UI framework at some point after 1.2 and I'd rather not create additional work for that rewrite.

2025-04-28 06:35 UTC, closed without merging